import { Geist, Geist_Mono } from "next/font/google";
import { Onest } from "next/font/google";
import "./globals.css";
import Header from '@/components/common/Header';
// import Footer from '@/components/common/Footer';

import { Instrument_Sans } from "next/font/google";

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${instrumentSans.className}`}>

        <main>
          {children}
        </main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
